core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from core.frontviews import *


urlpatterns = [
    # venues
    path("", home, name="home"),    
    path("contact", contact, name="contact"),
    path("about", about, name="about"),
    path("schools", schooles, name="schooles"),
    path("faq", faq, name="faq"),
    
    # Add more URLs as ne
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

# from teams.views import delete_tdeam

urlpatterns = [

    path('pay/<int:id>/', initiate_payment, name='payment'),
    path('registration/', payment_view, name='registration'),
    path("calculate_age_choices/", calculate_age_choices, name="calculate_age_choices"),
    path("airtel-money/callback/", airtel_payment_callback, name="airtel_payment_callback"),
    path("get-athletes/", get_athletes, name="get-athletes"),
    path('payment/success/<str:transaction_id>/', payment_success, name='payment_success'),
    path('athletes/data/', athletes_data, name='athletes_data'),
    path('schools/data/', schools_data, name='schools_data'),
    # ===================School========================,
    path("deleteschool/<int:id>", DeleteSchool, name="delschool"),
    path("schools/", schools, name="schools"),
    path("school/", Dash, name="school_dashboard"),
    path("addschool/", Schoolnew, name="new_school"),
    path("school/<int:id>", school_detail, name="schooldetail"),
    path("editschool/", school_update, name="schoolupdate"),
    
    # ===================Athletes========================,
    path("athletexs", athletexs, name="athletexs"),
    # path("athletes", athletes, name="athletes"),
    path("addathlete", newAthlete, name="addathlete"),
    path("athlete/<int:id>", AthleteDetail, name="athlete"),
    path("updateathlete/<int:id>", AthleteUpdate, name="updateathlete"),
    path("deleteathlete/<int:id>", DeleteAthlete, name="delathlete"),
    
   # ===================Officials========================,
    path("officials", school_offs, name="officials"),
    path("all_athletes/", all_athletes, name="athletex"),
    path("addofficial", Official, name="addofficial"),
    path("official/<int:id>", OfficialDetail, name="official"),
    path("all_officials/", all_officials, name="all_officials"),
       
   # ===================Officials========================,
    path("accounts/", accounts, name="accounts"),
    path("payments/", payments, name="payments"),
    path("pending_payments/", pending_payments, name="pending_payments"),
    path("activate_payment/<int:id>", activate_payment, name="activate_payment"),
    path("payment_detail/<int:id>", payment_detail, name="payment_detail"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re
from django.db import models
from accounts.models import *
from datetime import date
from django.core.exceptions import ValidationError


# Create your models here.
# Create your models here.


class School(models.Model):
    user = models.ForeignKey(
        User, related_name="school_profile", on_delete=models.CASCADE, null=True
    )
    school_name = models.CharField(max_length=100)
    status = models.CharField(
        max_length=19,
        choices=[("Active", "Active"), ("Inactive", "Inactive")],
        default="Inactive",
    )
    badge = models.ImageField(
        upload_to="badge/",
        blank=True,
        null=True,
    )
    EMIS = models.CharField(max_length=100, unique=True)
    center_number = models.CharField(max_length=100, null=True, blank=True, unique=True)
    district = models.ForeignKey(
        District,
        related_name="district",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    region = models.ForeignKey(
        Region,
        related_name="region",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    # headteacher
    lname = models.CharField(max_length=100)
    fname = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    nin = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    gender = models.CharField(
        max_length=1,
        choices=[("M", "Male"), ("F", "Female")],
    )
    photo = models.ImageField(
        upload_to="badge/",
        blank=True,
        null=True,
    )

    # games teacher
    gfname = models.CharField(max_length=100, null=True, blank=True, default="")
    glname = models.CharField(max_length=100, null=True, blank=True, default="")
    gemail = models.EmailField(null=True, blank=True, default="")
    gphone = models.CharField(max_length=15, null=True, blank=True, default="")
    gnin = models.CharField(max_length=20, default="")
    gdate_of_birth = models.DateField()
    ggender = models.CharField(
        max_length=1,
        choices=[("M", "Male"), ("F", "Female")],
        null=True,
        blank=True,
    )
    gphoto = models.ImageField(
        upload_to="badge/",
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.school_name


class school_official(models.Model):
    school = models.ForeignKey(School, related_name="school", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, blank=True, default="")
    email = models.EmailField(null=True, blank=True, default="")
    phone_number = models.CharField(max_length=15, null=True, blank=True, default="")
    nin = models.CharField(max_length=20, default="")
    date_of_birth = models.DateField()
    gender = models.CharField(
        max_length=1,
        choices=[("M", "Male"), ("F", "Female")],
        null=True,
        blank=True,
    )
    role = models.CharField(
        max_length=40,
        choices=[
            ("Coach", "Coach"),
            ("Teacher", "Teacher"),
            ("Assistant Games Teacher", "Assistant Games Teacher"),
            ("Assistant Head Teacher", "Assistant Head Teacher"),
            ("Nurse", "Nurse"),
            ("Doctor", "Doctor"),
            ("District Education Officer", "District Education Officer"),
            ("District Sports Officer", "District Sports Officer"),
        ],
        null=True,
        blank=True,
    )

    photo = models.ImageField(
        upload_to="badge/",
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name


class Classroom(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Age(models.Model):
    name = models.CharField(max_length=255)
    min_age = models.IntegerField(blank=True, null=True)
    max_age = models.IntegerField(blank=True, null=True)

    def clean(self):
        if (
            self.min_age is not None
            and self.max_age is not None
            and self.min_age > self.max_age
        ):
            raise ValidationError(
                "Minimum age must be less than or equal to maximum age."
            )

    def __str__(self):
        return self.name


class AthleteManager(models.Manager):
    def get_queryset(self):
        today = date.today()
        queryset = super().get_queryset()
        queryset = queryset.filter(date_of_birth__lte=today)
        return queryset.annotate(
            calculated_age=models.ExpressionWrapper(
                today.year - models.F("date_of_birth__year"),
                output_field=models.IntegerField(),
            )
        )

    def filter_by_age_range(self, min_age, max_age):
        return self.get_queryset().filter(
            calculated_age__gte=min_age, calculated_age__lte=max_age
        )




class Athlete(models.Model):
    fname = models.CharField(max_length=255)
    mname = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    lname = models.CharField(max_length=255)
    lin = models.CharField(max_length=255, unique=True)

    sport = models.ForeignKey(Sport, related_name="sport", on_delete=models.CASCADE)
    school = models.ForeignKey(
        School, related_name="schooler", on_delete=models.CASCADE
    )
    date_of_birth = models.DateField()
    gender = models.CharField(
        choices=[("Male", "male"), ("Female", "female")], max_length=10
    )
    classroom = models.ForeignKey(
        Classroom, related_name="classroom", on_delete=models.CASCADE
    )
    age = models.ForeignKey(Age, related_name="age", on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="athlete_photos/")

    Parent_fname = models.CharField(max_length=100)
    Parent_lname = models.CharField(max_length=100)
    parent_phone_number = models.CharField(max_length=15)
    parent_nin = models.CharField(max_length=20)
    address = models.CharField(max_length=20)
    designation = models.CharField(max_length=20)
    relationship = models.CharField(
        max_length=15,
        choices=[("Father", "Father"), ("Mother", "Mother"), ("Other", "Other")],
        null=True,
        blank=True,
    )
    # New field to track payment status
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    status = models.CharField(
        max_length=10,
        choices=[("ACTIVE", "ACTIVE"),("NEW", "NEW"), ("Inactive", "Inactive")],
        null=True,
        blank=True,
        default="NEW",
    )
    objects = AthleteManager()

    def save(self, *args, **kwargs):
        # Find the corresponding age range and assign it to the athlete
        age = date.today().year - self.date_of_birth.year
        age_range = Age.objects.filter(min_age__lte=age, max_age__gte=age).first()
        self.age = age_range

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.fname} {self.lname} {self.lin}"





class Payment(models.Model):

        transaction_id = models.CharField(max_length=100,null=True, blank=True)
        amount = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
     
        phone_number = models.CharField(max_length=15)
        status = models.CharField(
        max_length=20, 
        choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], 
        default='PENDING'
    )
  
        created_at = models.DateTimeField(auto_now_add=True)
        school = models.ForeignKey(School, on_delete=models.CASCADE)
        athletes = models.ManyToManyField(Athlete, related_name='payments')
        
        def __str__(self):
            return f"{self.transaction_id} - {self.amount} {self.school}"
            
                
        def clean(self):
            """Validate phone number format."""
            if not re.match(r'^(075|074|070)\d{7}$', self.phone_number):
                raise ValidationError("Phone number must a valid Airtel money number.")

        def save(self, *args, **kwargs):
            """Ensure validation before saving."""
            self.clean()
            super().save(*args, **kwargs)

school/templates/officials/NOfficial.html
{% extends "dashboard/dashboard.html" %}
<!---->
{% load static %}
<!---->
{%block title%}Officials{% endblock %}
<!---->
{% block content %}

<style>
  .alert {
    padding: 10px;
    margin-bottom: 10px;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  .error-message {
    background-color: red;
    color: white;
  }

  .success-message {
    background-color: #4caf50;
    color: white;
  }
</style>
<div id="app-content">
  <!-- Container fluid -->
  <div class="app-content-area">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
          <!-- Page header -->
          <div class="mb-5">
            <h2>Official Info</h2>
            <p>All fields labeled with <span>*</span> must be filled.</p>
          </div>
        </div>
      </div>
      <div>
        <!-- row -->
        <div class="row">
          <div class="col-12">
            <div class="card">
              <form
                action=""
                method="POST"
                class="form-ctrl card-body"
                enctype="multipart/form-data"
                id="regeForm"
              >
                {% csrf_token %} {% csrf_token %}
                <div class="fields">
                  <div class="leftp">
                    {% if messages %}
                    <div class="messages">
                      {% for message in messages %}
                      <div
                        class="alert {% if message.tags == 'error' %}error-message{% elif message.tags == 'success' %}success-message{% endif %}"
                      >
                        {{ message }}
                      </div>
                      {% endfor %}
                    </div>
                    {% endif %}
                    <div class="row">
                      <div class="col-md-4">
                        <div
                          class="field"
                          style="
                            background-image: url('https://upssaonline.com/profile.png');
                            background-size: cover;
                            background-position: center;
                            padding: 20px;
                            height: 350px;
                            width: 100%;
                          "
                        >
                          <div
                            id="photos_preview"
                            class="preview-container"
                          ></div>
                        </div>
                        <div class="field mt-2">
                          <input
                            type="file"
                            name="photo"
                            accept="image/*"
                            id="id_photo"
                          />
                        </div>
                      </div>

                      <div class="col-md-8">
                        <div class="row">
                          <div class="col-md-6 mb-3">
                            <label>Name</label>{{form.name}}
                          </div>
                          <div class="col-md-6 mb-3">
                            <label>National ID number</label>{{form.nin}}
                          </div>
                          <div class="col-md-6 mb-3">
                            <label>Email</label>{{form.email}}
                          </div>
                          <div class="col-md-6 mb-3">
                            <label>Contact</label>{{form.phone_number}}
                          </div>
                          <div class="col-md-6 mb-3">
                            <label>Gender</label>{{form.gender}}
                          </div>
                          <div class="col-md-6 mb-3">
                            <label>Date of Birth</label>{{form.date_of_birth}}
                          </div>
                          <div class="col-md-6 mb-3">
                            <label>Role</label>{{form.role}}
                          </div>
                        </div>

                        <button type="submit" class="btn btn-primary">
                          Save Official
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
  <script src="{% static 'js/photo.js' %}"></script>
</div>
{% endblock %}

school/templates/officials/official.html
{% extends "dashboard/dashboard.html" %}
<!---->
{% load static %}
<!---->

{% block title %}{{official.fname}} {{official.lname}}
<!---->
{% endblock %} {% block content %}
<div id="app-content">
  <!-- Container fluid -->
  <div class="app-content-area">
    <div class="container-fluid">
      <div class="athlete-dew content-wrapper">
        <div class="row">
          <div class="col-md-4">
            <img src="{{official.photo.url}}" alt="" />
          </div>
          <div class="col-md-8">
            <h1>{{official.name}}</h1>
            <p>{{official.email}}</p>
            <hr />
            <div class="info-ath">
              <span
                >National Identification number:
                <h3>{{official.nin}}</h3></span
              >
              <span
                >Role:
                <h3>{{official.role}}</h3></span
              >

              <span
                >Contact:
                <h3>{{official.phone_number}}</h3></span
              >

              <span
                >Date of Birth:
                <h3>{{official.date_of_birth}}</h3></span
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

school/templates/officials/officials.html
{% extends "dashboard/dashboard.html" %}
<!---->
{% load static %}
<!---->

<!---->
{%block title%}Officials{% endblock %}
<!---->
{% block content %}
<div id="app-content">
  <!-- Container fluid -->
  <div class="app-content-area">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
          <!-- Page header -->
          <div class="mb-5">
            <h3 class="mb-0">Officials</h3>
          </div>
        </div>
      </div>
      <div>
        <!-- row -->
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-md-flex border-bottom-0">
                <div class="mt-3 mt-md-0">
                  <a
                    href="#!"
                    class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                    data-template="settingOne"
                  >
                    <i data-feather="settings" class="icon-xs"></i>
                    <div id="settingOne" class="d-none">
                      <span>Setting</span>
                    </div>
                  </a>

                  <a href="#!" class="btn btn-outline-white ms-2">Import</a>
                  <a href="#!" class="btn btn-outline-white ms-2">Export</a>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive table-card">
                  <table
                    id="example"
                    class="table text-nowrap table-centered mt-0"
                    style="width: 100%"
                  >
                    <thead class="table-light">
                      <tr>
                        <th class="ps-1">Official</th>
                        <th>School</th>
                        <th>Role</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for official in officilas %}
                      <tr>
                        <td class="pe-0">
                          <div class="d-flex align-items-center">
                            {% if official.photo %}
                            <img
                              src="{{official.photo.url}}"
                              alt=""
                              class="img-4by3-sm rounded-3"
                              style="
                                width: 30px;
                                height: 30px;
                                object-fit: cover;
                              "
                            />
                            {% else %}
                            <img
                              src="{% static 'images/fav.png'%}"
                              alt=""
                              class="img-4by3-sm rounded-3"
                              style="
                                width: 30px;
                                height: 30px;
                                object-fit: cover;
                              "
                            />{% endif %}
                            <div class="ms-3">
                              <h5 class="mb-0">
                                <a
                                  href="{% url 'official' official.id%}"
                                  class="text-inherit"
                                  >{{official.first_name}}
                                  {{official.last_name}}
                                </a>
                              </h5>
                            </div>
                          </div>
                        </td>
                        <td>{{official.school}}</td>
                        <td>{{official.role}}</td>
                        <td>{{official.phone_number}}</td>

                        <td>
                          <span class="badge badge-success-soft"
                            >{{official.email}}</span
                          >
                        </td>
                        <td>
                          <a
                            href="#!"
                            class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                            data-template="eyeOne"
                          >
                            <i data-feather="eye" class="icon-xs"></i>
                            <div id="eyeOne" class="d-none">
                              <span>View</span>
                            </div>
                          </a>
                          <a
                            href="#!"
                            class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                            data-template="editOne"
                          >
                            <i data-feather="edit" class="icon-xs"></i>
                            <div id="editOne" class="d-none">
                              <span>Edit</span>
                            </div>
                          </a>
                          <a
                            href="#!"
                            class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                            data-template="trashOne"
                          >
                            <i data-feather="trash-2" class="icon-xs"></i>
                            <div id="trashOne" class="d-none">
                              <span>Delete</span>
                            </div>
                          </a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- row -->
      </div>
    </div>
  </div>
  <!-- Container fluid -->
</div>
{% endblock %}

school/templates/officials/school_officials.html
{% extends "dashboard/dashboard.html" %}
<!---->
{% load static %}
<!---->
{%block title%}Officials{% endblock %}
<!---->

<!---->
{% block content %}
<div id="app-content">
  <!-- Container fluid -->
  <div class="app-content-area">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
          <!-- Page header -->
          <div class="mb-5">
            <h3 class="mb-0">Officials</h3>
          </div>
        </div>
      </div>
      <div>
        <!-- row -->
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header d-md-flex border-bottom-0">
                <div class="flex-grow-1">
                  <a href="{% url 'addofficial'%}" class="btn btn-primary"
                    >+ Add Official</a
                  >
                </div>
            
              </div>
              <div class="card-body">
                <div class="table-responsive table-card">
                  <table
                    id="example"
                    class="table text-nowrap table-centered mt-0"
                    style="width: 100%"
                  >
                    <thead class="table-light">
                      <tr>
                        <th class="ps-1">Official</th>
                        <th>School</th>
                        <th>Role</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for official in school_offs %}
                      <tr>
                        <td class="pe-0">
                          <div class="d-flex align-items-center">
                            {% if official.photo %}
                            <img
                              src="{{official.photo.url}}"
                              alt=""
                              class="img-4by3-sm rounded-3"
                              style="
                                width: 30px;
                                height: 30px;
                                object-fit: cover;
                              "
                            />
                            {% else %}
                            <img
                              src="{% static 'images/fav.png'%}"
                              alt=""
                              class="img-4by3-sm rounded-3"
                              style="
                                width: 30px;
                                height: 30px;
                                object-fit: cover;
                              "
                            />{% endif %}
                            <div class="ms-3">
                              <h5 class="mb-0">
                                <a
                                  href="{% url 'official' official.id%}"
                                  class="text-inherit"
                                  >{{official.name}}
                                 
                                </a>
                              </h5>
                            </div>
                          </div>
                        </td>
                        <td>{{official.school}}</td>
                        <td>{{official.role}}</td>
                        <td>{{official.phone_number}}</td>

                        <td>
                          <span class="badge badge-success-soft"
                            >{{official.email}}</span
                          >
                        </td>
                        <td>
                          <a
                            href="#!"
                            class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                            data-template="eyeOne"
                          >
                            <i data-feather="eye" class="icon-xs"></i>
                            <div id="eyeOne" class="d-none">
                              <span>View</span>
                            </div>
                          </a>
                          <a
                            href="#!"
                            class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                            data-template="editOne"
                          >
                            <i data-feather="edit" class="icon-xs"></i>
                            <div id="editOne" class="d-none">
                              <span>Edit</span>
                            </div>
                          </a>
                          <a
                            href="#!"
                            class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip"
                            data-template="trashOne"
                          >
                            <i data-feather="trash-2" class="icon-xs"></i>
                            <div id="trashOne" class="d-none">
                              <span>Delete</span>
                            </div>
                          </a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- row -->
      </div>
    </div>
  </div>
  <!-- Container fluid -->
</div>
{% endblock %}